### ISSUE TITLE
Complex rules don't work

### ISSUE THREAD

**Issue by rabutler-usbr** [BoulderCodeHub/RWcheck#1]
More complex rules are failing with `Error in parse(text = x$expr)[[1]] : subscript out of bounds`

The following two rules both break the code. The first because there is a space in `Mead.Pool Elevation`. The second is just not working properly. 

yaml:
```
# check ub res outflow >= 0
rules:
-
  expr: Mead.Pool Elevation > 0
  name: Mead.Pool Elevation
  label: Mead PE
  description: |
    Mead PE should never be NA
  in_file: KeySlots.rdf
-
  expr: !isNA(SummaryOutputData.EqualizationAbove823)
  name: EqualizationAbove823
  label: Equalization Above 823
  description: |
    Equalization ABove 823 should never be NA
  in_file: SystemConditions.rdf
```

--------------

if you create the yaml file as specified above, the following code can be used to test it:

```
scenarios <- c("Feb2020_2021,ISM1988_2018,2007Dems,IG_DCP,MTOM_Most",
               "Feb2020_2021,ISM1988_2018,2007Dems,NA,MTOM_Most")
scenario_dir <- "M:/Shared/CRSS/2020/Scenario"
output_dir <- "C:/alan/CRSS/CRSS.2020/results/feb2020/RWcheck"
yaml_dir <- getwd()

yaml_rule_files <- "test_crss.yaml"

check_slots(scenarios,
              yaml_rule_files,
              scenario_dir,
              output_dir,
              yaml_dir)

```
